on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

jobs:
  build_ui:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 16
        uses: actions/setup-node@v6
        with:
          node-version: 16.9.1
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run build
