on:
  push:
    branches: [master]
  workflow_dispatch:
  pull_request:

jobs:
  build_ui:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ui

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 22.17.0
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run build
